Account update delete
FedeOt/ot-upcamp pull request #3
Opened 2022-09-22 17:13 UTC by FedeOt

-Adds a component to update and delete the accounts
-Adds a new feature in the login to know who's logged
-Adds unit test to the update component.

2022-09-27 14:47 UTC, santiago-abstracta requested changes

2022-09-27 14:47 UTC, ghost commented on src/axios/Instance.js
> +export const getRole = () => sessionStorage.getItem('role');
I'd put it in a login-related functions file.

2022-09-27 14:47 UTC, ghost commented on src/api/index.js
> +    }
You can use the _Ternary Opeator_ here.

2022-09-27 14:47 UTC, ghost commented on src/api/index.js
> +    params:{newName:data}});
If `data` only stores the Account Name, I'd name this parameter `name` instead.

2022-09-27 14:47 UTC, ghost commented on src/index.css
> +
Could you remove these spaces? :)

2022-09-27 14:47 UTC, ghost commented on src/components/UpdateInput.jsx
> +      console.log(inputValue);
This line isn't necessary anymore, right?

2022-09-27 14:47 UTC, ghost commented on src/components/UpdateInput.jsx
> +      }
You can use the _Ternary Operator_ here.

2022-09-27 14:47 UTC, ghost commented on src/components/UpdateInput.jsx
> +}
Format this file, please.

2022-09-27 14:47 UTC, ghost commented on src/components/AccountCard.jsx
> +  const [inputOpen,setInputOpen] = useState(false);
Is this the New Name input?

2022-09-27 14:47 UTC, ghost commented on src/components/AccountCard.jsx
> +    console.log(response.status);
Can you remove this line?

2022-09-27 14:47 UTC, ghost commented on src/tests/AccountUpdate.test.js
> +const INPUTVALUE = "New account";
Use `camelCase`.

2022-09-27 14:47 UTC, ghost commented on src/tests/AccountUpdate.test.js
> +        expect(updateInput).not.toBeInTheDocument();
You should add an assertion to check if the Account Name changed after updating it.

2022-09-27 14:47 UTC, ghost commented on src/tests/AccountUpdate.test.js
> +})
Remember to format this file, please! :)

2022-09-27 17:42 UTC, FedeOt commented on src/tests/AccountUpdate.test.js
> +})
Done!

2022-09-27 17:42 UTC, FedeOt commented on src/tests/AccountUpdate.test.js
> +const INPUTVALUE = "New account";
Done!

2022-09-27 17:43 UTC, FedeOt commented on src/components/AccountCard.jsx
> +    console.log(response.status);
Do you mean the console.log?

2022-09-27 17:44 UTC, FedeOt commented on src/components/AccountCard.jsx
> +  const [inputOpen,setInputOpen] = useState(false);
That useState is opening and closing the new name input, depending on the state

2022-09-27 17:48 UTC, FedeOt commented on src/components/UpdateInput.jsx
> +      console.log(inputValue);
the console.log is not necessary anymore

2022-09-27 17:49 UTC, FedeOt commented on src/api/index.js
> +    params:{newName:data}});
Done!

2022-09-27 17:50 UTC, FedeOt commented on src/index.css
> +
Yes

2022-09-29 20:14 UTC, santiago-abstracta commented on src/components/AccountCard.jsx
> +    console.log(response.status);
Yes!

2022-09-29 20:18 UTC, santiago-abstracta approved these changes
Looks good to me!

2022-09-30 11:37 UTC, merged